<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="126" started-at="2022-04-15T16:39:40 IST" finished-at="2022-04-15T16:39:40 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="126" started-at="2022-04-15T16:39:40 IST" finished-at="2022-04-15T16:39:40 IST">
      <class name="POMsaucedemopractice.TestNG4">
        <test-method status="FAIL" signature="verifiylogin()[pri:0, instance:POMsaucedemopractice.TestNG4@5ed828d]" name="verifiylogin" duration-ms="21" started-at="2022-04-15T16:39:40 IST" finished-at="2022-04-15T16:39:40 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title are not match expected [Swag labs] but found [swag labs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title are not match expected [Swag labs] but found [swag labs]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at POMsaucedemopractice.TestNG4.verifiylogin(TestNG4.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifiylogin -->
        <test-method status="PASS" signature="verifiyproduct()[pri:0, instance:POMsaucedemopractice.TestNG4@5ed828d]" name="verifiyproduct" duration-ms="5" started-at="2022-04-15T16:39:40 IST" finished-at="2022-04-15T16:39:40 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifiyproduct -->
      </class> <!-- POMsaucedemopractice.TestNG4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
